version: '3.7'

services:
  seq:
    image: datalust/seq:latest
    restart: always
    ports: 
      - "8080:80"
      - "5341:5341"
    environment:
      - ACCEPT_EULA=Y
  mongodb:
    container_name: monitoring-mongo
    restart: always
    image: mongo:latest
    environment:
      - "MONGO_DATA_DIR=/data/db"        
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=4321
#    volumes:
#      - "./mongo:/data/db"
#      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    ports:
      - "27017:27017"

  