version: '3.7'

services:
  seq:
    image: datalust/seq:latest
    restart: always
    ports: 
      - "8080:80"
      - "5341:5341"
    environment:
      - ACCEPT_EULA=Y
  mongodb:
    container_name: monitoring-mongo
    entrypoint:
      - bash
      - -c
      - |
        echo testtoken > /data/replica.key
        chmod 400 /data/replica.key
        chown 999:999 /data/replica.key
        exec docker-entrypoint.sh $$@    
    command: "mongod --bind_ip_all --replSet rs1 --keyFile /data/replica.key"
    restart: always
    image: mongo:latest
    environment:
      - "MONGO_DATA_DIR=/data/db"        
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=4321
      - MONGO_INITDB_DATABASE=monitoring
    #    volumes:
#      - ./mongo.key:/etc/mongo-replication.key
#      - "./mongo:/data/db"
#      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    ports:
      - "27017:27017"
  teamcity-server:
    image: jetbrains/teamcity-server:latest
    ports:
      - "8112:8111"
   # volumes:
   #   - ./teamcity-server/data:C:/ProgramData/JetBrains/TeamCity
   #   - ./teamcity-server/logs:C:/TeamCity/logs
    deploy:
      resources: 
        limits:
          memory: 2g
    #mem_limit: 2g
  teamcity-agent:
      image: jetbrains/teamcity-agent:2021.1-linux-sudo
      privileged: true
      environment:
        - DOCKER_IN_DOCKER=start
        - SERVER_URL=http://teamcity-server:8111
        - TEAMCITY_SERVER_MEM_OPTS=-Xmx2g -XX:ReservedCodeCacheSize=350m
#  